### ISSUE TITLE
Neuer Fragenkatalog ab 1. August 2023

### ISSUE THREAD

**Issue by jokober** [kralo/elwis-anki-parser#1]
Cooles Tool. Ab 1. August  werden neue Fragen geprüft: https://www.elwis.de/DE/Sportschifffahrt/Sportbootfuehrerscheine/Fragenkatalog-Binnen-neu/Fragenkatalog-Binnen-neu-node.html

Als ich schauen wollte, ob dein Tool noch läuft bin ich leider auf efolgenden Fehler gestoßen
`error: Compile server encountered fatal condition: javax/tools/DiagnosticListener
java.lang.ClassNotFoundException: javax.tools.DiagnosticListener
`
Leider kenne ich mich mit Scala noch nicht aus und habe gerade keine Zeit mich reinzufuchsen. Daher wollt ich nur auf den aktuellen Fragenkatalog hinweisen. Grüße

**Comment by kralo** [comment]
Ja scheint nicht mehr zu gehen. Ich mach das morgen mal neu.

**Comment by kralo** [comment]
neues Release, Dateien für direkten Anki-Import unter `releases`

**Comment by jokober** [comment]
Cool, danke dafür! Allerdings kann ich das .apkg leider nicht importieren. Ich bekomme folgenden Fehler in Anki: "A number was invalid or out of range."

**Comment by kralo** [comment]
Habe eben gerade nochmal mit Anki Desktop probiert da lassen sich beide Pakete problemlos laden.

**Comment by jokober** [comment]
Ich konnte die Pakete von der Anki Android App aus laden. Keine Ahnung warum es nicht mit Anki Desktop (linux) funktioniert hat. Danke dir!
