### ISSUE TITLE
500: A number was invalid or out of range.

### ISSUE THREAD

**Issue by UraniumDonut** [kralo/elwis-anki-parser#3]
Beim Importieren des Decks erscheint der Fehler 
`500: A number was invalid or out of range.`
Sowohl auf newest Windows als auch auf Android :/
Kann gerne logs schicken, wenn ich weiss wie das geht :)

**Comment by kralo** [comment]
und bricht es ab oder kannst du einfach "OK" und weiter und alles ist top?

**Comment by UraniumDonut** [comment]
![image](https://github.com/kralo/elwis-anki-parser/assets/75068550/fcd3fc4e-01ae-406f-a909-6f5788f850b8)
Es ist kein OK Knopf sichtbar. Das schließen des Fehlerfensters bricht den import-process ab.

btw wow, das ist die schnellste Antwort auf ein Issue, die ich je gekriegt habe

**Comment by UraniumDonut** [comment]
Ich habe es mit einer historischen anki version (2.1.56) probiert. Das Fehlerfenster sieht anders aus, aber sonst ist alles identisch. 
![image](https://github.com/kralo/elwis-anki-parser/assets/75068550/3a674cbb-c767-4231-9bdb-1dbe2eeac201)

**Comment by UraniumDonut** [comment]
```
Traceback (most recent call last):
  File "aqt.mediasrv", line 629, in wrapped
  File "aqt.mediasrv", line 515, in import_anki_package
  File "aqt.mediasrv", line 497, in import_request
  File "aqt.mediasrv", line 610, in <lambda>
  File "anki._backend_generated", line 1865, in import_anki_package_raw
  File "anki._backend", line 173, in _run_command
anki.errors.InvalidInput: A number was invalid or out of range.
```

Hab einen Error log herausgefischt

**Comment by kralo** [comment]
hi, sieht so aus als hätten die sich royal verfriemelt. 
Habe alte Versionen durchgetestet und es "ging mal" und wurde schlecht.

Beim neusten Anki läuft es bei mir mit Extras->Einstellungen->Bearbeiten->"Legacy Import/Export"

**Comment by jottr** [comment]
Bitte schreibe das doch ins README.
